// Shared exhibitor data — read by artist.html to render individual profile pages.
// Fill in real work titles, genres, bios, and social links as they're confirmed.

var EXHIBITORS = [
  {
    id: "artist-01",
    name: "Yuki Tanaka",
    work: "無題",
    genre: "ミクストメディア",
    bio: "作家ステートメント準備中。",
    social: { web: "#", x: "#", instagram: "#" },
  },
  {
    id: "artist-02",
    name: "長谷川 凛太",
    work: "無題",
    genre: "ミクストメディア",
    bio: "作家ステートメント準備中。",
    social: { web: "#", x: "#", instagram: "#" },
  },
  {
    id: "artist-03",
    name: "Manato Tominaga",
    work: "無題",
    genre: "ミクストメディア",
    bio: "作家ステートメント準備中。",
    social: { web: "#", x: "#", instagram: "#" },
  },
  {
    id: "artist-04",
    name: "莉山 (A)",
    work: "無題",
    genre: "ミクストメディア",
    bio: "作家ステートメント準備中。",
    social: { web: "#", x: "#", instagram: "#" },
  },
  {
    id: "artist-05",
    name: "Kazuki Fukuyo",
    work: "無題",
    genre: "ミクストメディア",
    bio: "作家ステートメント準備中。",
    social: { web: "#", x: "#", instagram: "#" },
  },
  {
    id: "artist-06",
    name: "Rui",
    work: "無題",
    genre: "ミクストメディア",
    bio: "作家ステートメント準備中。",
    social: { web: "#", x: "#", instagram: "#" },
  },
  {
    id: "artist-07",
    name: "imechiumaya",
    work: "無題",
    genre: "ミクストメディア",
    bio: "作家ステートメント準備中。",
    social: { web: "#", x: "#", instagram: "#" },
  },
  {
    id: "artist-08",
    name: "soshi yoshida",
    work: "無題",
    genre: "ミクストメディア",
    bio: "作家ステートメント準備中。",
    social: { web: "#", x: "#", instagram: "#" },
  },
  {
    id: "artist-09",
    name: "TANDA",
    work: "無題",
    genre: "ミクストメディア",
    bio: "作家ステートメント準備中。",
    social: { web: "#", x: "#", instagram: "#" },
  },
  {
    id: "artist-10",
    name: "Scott Allen",
    work: "無題",
    genre: "ミクストメディア",
    bio: "作家ステートメント準備中。",
    social: { web: "#", x: "#", instagram: "#" },
  },
];
